/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated/ventes'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedDepensesRouteImport } from './routes/_authenticated/depenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepensesRoute = AuthenticatedDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depenses': typeof AuthenticatedDepensesRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/_authenticated/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/catalogue'
    | '/dashboard'
    | '/depenses'
    | '/rapports'
    | '/stock'
    | '/utilisateurs'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/catalogue'
    | '/dashboard'
    | '/depenses'
    | '/rapports'
    | '/stock'
    | '/utilisateurs'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/catalogue'
    | '/_authenticated/dashboard'
    | '/_authenticated/depenses'
    | '/_authenticated/rapports'
    | '/_authenticated/stock'
    | '/_authenticated/utilisateurs'
    | '/_authenticated/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/depenses': {
      id: '/_authenticated/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AuthenticatedDepensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepensesRoute: typeof AuthenticatedDepensesRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepensesRoute: AuthenticatedDepensesRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
  AuthenticatedVentesRoute: AuthenticatedVentesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
